const PokemonTypes = {
  TYPE_NORMAL: 'NORMAL',
  TYPE_FIRE: 'FIRE',
  TYPE_FIGHTING: 'FIGHTING',
  TYPE_WATER: 'WATER',
  TYPE_FLYING: 'FLYING',
  TYPE_GRASS: 'GRASS',
  TYPE_POISON: 'POISON',
  TYPE_ELECTRIC: 'ELECTRIC',
  TYPE_GROUND: 'GROUND',
  TYPE_PSYCHIC: 'PSYCHIC',
  TYPE_ROCK: 'ROCK',
  TYPE_ICE: 'ICE',
  TYPE_BUG: 'BUG',
  TYPE_DRAGON: 'DRAGON',
  TYPE_DARK: 'DARK',
  TYPE_STEEL: 'STEEL',
  TYPE_FAIRY: 'FAIRY',
  TYPE_GHOST: 'GHOST'
};

export {
  PokemonTypes
};
